# frozen_string_literal: true

Vagrant.configure('2') do |config|
  ENV['LC_ALL'] = 'en_US.UTF-8'
  config.vm.box = 'fedora/41-cloud-base'
  config.vm.box_version = '41-20241024.0'

  # 16,67 mins
  config.vm.boot_timeout = 1000
  config.vm.hostname = 'host'
  config.vm.network 'private_network', type: 'dhcp'

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder '../../module', '/home/vagrant/module', type: 'rsync'

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = '2048'
    libvirt.cpus = 4
    libvirt.default_prefix = 'LetheFedora'
    libvirt.storage_pool_name = 'default'
    libvirt.qemu_use_session = false
    libvirt.keymap = 'en-us'
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '2048'
    vb.cpus = 4
    vb.name = 'LetheFedora'
    vb.gui = false
    vb.check_guest_additions = false
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.provision 'shell', path: '../../scripts/fedora.sh'
  config.vm.provision 'shell', path: '../../scripts/tweaks.sh'
  config.vm.provision :reload

  # config.vm.provision 'shell', path: '../../scripts/kernel.sh'
  config.vm.provision :reload
end
